module dqz_to_pwm_tb;

localparam PERIOD = 10;
localparam DATA_WIDTH = 16; // 16-bit signed data
localparam ADDR_WIDTH = 11; // Increased from 10 to allow counting up to 1199

integer i, k;
reg clk;
reg clk_720;
reg reset;
reg [ADDR_WIDTH-1:0] addr_cnt;

// Memory arrays for stimulus
reg signed [DATA_WIDTH-1:0] mem_phase_a     [0:3000];
reg signed [DATA_WIDTH-1:0] mem_phase_b     [0:3000];
reg signed [DATA_WIDTH-1:0] mem_phase_c     [0:3000];
reg signed [DATA_WIDTH-1:0] mem_sine_ramp   [0:3000];
reg signed [DATA_WIDTH-1:0] mem_cosine_ramp [0:3000];
reg [31:0] mem_freq_ref [0:3000];

// Wires to connect to UUT
wire signed [DATA_WIDTH-1:0] sig_a, sig_b, sig_c;
wire signed [DATA_WIDTH-1:0] sig_s, sig_cos;
wire signed [17:0] d_out, q_out;

// 1. Load the Hex files generated by MATLAB
initial begin
    $readmemh("grid_a.hex",     mem_phase_a);
    $readmemh("grid_b.hex",     mem_phase_b);
    $readmemh("grid_c.hex",     mem_phase_c);
    $readmemh("sine_ramp.hex",   mem_sine_ramp);
    $readmemh("cosine_ramp.hex", mem_cosine_ramp);
	 $readmemh("freq_ref.hex", mem_freq_ref);
    
    $display("Data loaded into testbench memories.");
end

// 3. Address Counter / Sequencer
// ... (Keep your existing parameters)
 // Add these new timing parameters:
 localparam CLK_FREQ_HZ     = 25_000_000;  // 25 MHz System Clock
 localparam SAMPLE_RATE_HZ  = 720;         // Target Data Rate
 localparam CLKS_PER_SAMPLE = CLK_FREQ_HZ / SAMPLE_RATE_HZ; // ~34,722 clocks
 
 localparam FAST_CONV = 123695; // 0s32 of 720/25M
localparam CARRIER_CONV = 75; // 75 as in matlab

(* noprune *) wire u_high;
(* noprune *) wire u_low;
(* noprune *) wire v_high;
(* noprune *) wire v_low;
(* noprune *) wire w_high;
(* noprune *) wire w_low;


 integer timer_cnt;

 // 3. Address Counter / Sequencer (Modified for 720 Hz rate)
 // ALSO - HERE WE MAKE OUR 720 CLK ENABLE CALLED CLK 720
always @(posedge clk or posedge reset) begin
    if (reset) begin
      addr_cnt  <= 11'd0;
      timer_cnt <= 0;
      clk_720 <= 1'd0;
    end else begin
      // Check if enough clock cycles have passed to jump to the next sample
      if (timer_cnt >= CLKS_PER_SAMPLE - 1) begin
            timer_cnt <= 0;               // Reset timer
            clk_720 <= 1;
            
            // Seamless wrap logic:
            if (addr_cnt >= 11'd1199) begin
                addr_cnt <= 11'd0;        // Loop back to start of cycle
            end else begin
                addr_cnt <= addr_cnt + 11'd1; 
            end
            
      end else begin
            timer_cnt <= timer_cnt + 1;
            clk_720 <= 0;
      end
    end
 end

// 4. Assign memory values to UUT input wires
assign sig_a   = mem_phase_a[addr_cnt];
assign sig_b   = mem_phase_b[addr_cnt];
assign sig_c   = mem_phase_c[addr_cnt];
assign sig_s   = mem_sine_ramp[addr_cnt];
assign sig_cos = mem_cosine_ramp[addr_cnt];
wire [31:0] expected_freq = mem_freq_ref[addr_cnt];


// ===== Parameters for ipll =====
localparam WORD_SIZE = 18;        // 18-bit signed output
localparam ADDR_SIZE = 10;        // 10-bit addressing
localparam ACC_WIDTH = 32;        // 32-bit phase accumulator

// ===== Signals =====
wire signed [ACC_WIDTH-1:0] freq_out;

// ===== Clock Generation =====
initial begin
    clk = 0;
    forever begin 
        #(PERIOD/2);
        clk = ~clk;
    end
end

// ===== DUT Instantiation =====
/*
ipll dut (
    .clk(clk),
	 .clk_en(clk_720),
    .reset(reset),
    .q_in(q_out),
    .freq_out(freq_out)
);
*/

srf_pll_1 dut (
    .clk(clk),
	 .clk_en(clk_720),
    .reset(reset),
    .q_in(q_out),
    .freq_out(freq_out)
);

dqz dqz_inst (
  .clk(clk),
  .clk_en(clk_720),
  .reset(reset),
  .a_in(sig_a),
  .b_in(sig_b),
  .c_in(sig_c),
  .freq_in(freq_out),
  .d_out(d_out),
  .q_out(q_out) 
);


(* noprune *) wire signed [63:0] freq_out_fast_big = freq_out * FAST_CONV; // freq out - which is in cycles per sample at 720 samples/sec, into 25M samples/sec
(* noprune *) wire signed [31:0] freq_out_fast = freq_out_fast_big[63:32]; // Top 32 bits after multiplication
(* noprune *) wire signed [31:0] carrier_freq = freq_out_fast * CARRIER_CONV; // freq out fast multiplied by our modulation constant (75 I think)

/*
spwm - pulse width modulation - controls switches of inverter with GPIO
*/
inverter_top #(
        .WORD_SIZE(18),
        .ACC_WIDTH(32)
    ) inst_inverter_top (
        .clk(clk),
        .clk_en(clk_720),
        .reset(reset),
        .freq_in(freq_out_fast),
        .carrier_fcw(carrier_freq),
        .d_in(d_out),
        .q_in(q_out),
        .u_high(u_high),
        .u_low(u_low),
        .v_high(v_high),
        .v_low(v_low),
        .w_high(w_high),
        .w_low(w_low)
    );

integer freq_file;

initial begin
    freq_file = $fopen("DQZ_TO_SPVM_59HZ_SRF.txt", "w");
	 $display("OPENING IGNORE.txt");
    if (freq_file == 0) begin
        $display("Error: Could not open file for writing.");
        $finish;
    end
end

// Log the data every time the system updates (at the 720Hz rate)
always @(posedge clk) begin
    if (clk_720 && !reset) begin
        // %h writes in hex, %d for decimal. 
        // Hex is usually safer for 32-bit unsigned values to avoid sign-bit confusion.
        $fwrite(freq_file, "%h\n", freq_out); 
    end
end


// ===== Test Stimulus =====
initial begin
  // Initialize signals
  
  reset = 1;
  #(PERIOD * 5);
  reset = 0;
  #(PERIOD * 2048);

end

final begin
     $fclose(freq_file);
    $display("Hardware frequency data saved to IGNORE.txt");
end
endmodule