module dqz_to_ipll_tb;

localparam PERIOD = 10;
localparam DATA_WIDTH = 16; // 16-bit signed data
localparam ADDR_WIDTH = 11; // Increased from 10 to allow counting up to 1199

localparam [31:0] FCW_60HZ = 32'd10308;

integer i, k;
reg clk;
reg clk_720;
reg reset;
reg [ADDR_WIDTH-1:0] addr_cnt;
reg [31:0] theta;

// Memory arrays for stimulus
reg signed [DATA_WIDTH-1:0] mem_phase_a     [0:3000];
reg signed [DATA_WIDTH-1:0] mem_phase_b     [0:3000];
reg signed [DATA_WIDTH-1:0] mem_phase_c     [0:3000];
reg signed [DATA_WIDTH-1:0] mem_sine_ramp   [0:3000];
reg signed [DATA_WIDTH-1:0] mem_cosine_ramp [0:3000];
reg [31:0] mem_freq_ref [0:3000];

// Wires to connect to UUT
wire signed [DATA_WIDTH-1:0] sig_a, sig_b, sig_c;
wire signed [DATA_WIDTH-1:0] sig_s, sig_cos;
wire signed [17:0] d_out, q_out;

// 1. Load the Hex files generated by MATLAB
initial begin
    $readmemh("grid_a.hex",     mem_phase_a);
    $readmemh("grid_b.hex",     mem_phase_b);
    $readmemh("grid_c.hex",     mem_phase_c);
    $readmemh("sine_ramp.hex",   mem_sine_ramp);
    $readmemh("cosine_ramp.hex", mem_cosine_ramp);
	 $readmemh("freq_ref.hex", mem_freq_ref);
    
    $display("Data loaded into testbench memories.");
end

// 3. Address Counter / Sequencer
// ... (Keep your existing parameters)
 // Add these new timing parameters:
 localparam CLK_FREQ_HZ     = 25_000_000;  // 25 MHz System Clock
 localparam SAMPLE_RATE_HZ  = 720;         // Target Data Rate
 localparam CLKS_PER_SAMPLE = CLK_FREQ_HZ / SAMPLE_RATE_HZ; // ~34,722 clocks

 integer timer_cnt;

 // 3. Address Counter / Sequencer (Modified for 720 Hz rate)
 // ALSO - HERE WE MAKE OUR 720 CLK ENABLE CALLED CLK 720
always @(posedge clk or posedge reset) begin
    if (reset) begin
      addr_cnt  <= 11'd0;
      timer_cnt <= 0;
      clk_720 <= 1'd0;
    end else begin
      // Check if enough clock cycles have passed to jump to the next sample
      if (timer_cnt >= CLKS_PER_SAMPLE - 1) begin
            timer_cnt <= 0;               // Reset timer
            clk_720 <= 1;
            
            // Seamless wrap logic:
            if (addr_cnt >= 11'd1199) begin
                addr_cnt <= 11'd0;        // Loop back to start of cycle
            end else begin
                addr_cnt <= addr_cnt + 11'd1; 
            end
            
      end else begin
            timer_cnt <= timer_cnt + 1;
            clk_720 <= 0;
      end
    end
 end
 // ... (Rest of your module)
 
 // at least now our sig_a b c actually represent what they are actually going to look like 

// 4. Assign memory values to UUT input wires
assign sig_a   = mem_phase_a[addr_cnt];
assign sig_b   = mem_phase_b[addr_cnt];
assign sig_c   = mem_phase_c[addr_cnt];
assign sig_s   = mem_sine_ramp[addr_cnt];
assign sig_cos = mem_cosine_ramp[addr_cnt];
wire [31:0] expected_freq = mem_freq_ref[addr_cnt];
// So - sig a b c are loaded into dqz, which outputs vq (q_ii), which goes into ipll, which gives frequency (phase out), which goes back into dqz
// What to watch here is sig a vs sine (which will be in dqz instatiation) 
// as well as vq obviously 
// and phase out (which is the frequency)

// at the moment, all of this bull is probably totally wrong (like signal length wise and stuff), but its worth a shot 


// ===== Parameters for ipll =====
localparam WORD_SIZE = 18;        // 18-bit signed output
localparam ADDR_SIZE = 10;        // 10-bit addressing
localparam ACC_WIDTH = 32;        // 32-bit phase accumulator

// ===== Signals =====
wire  signed [WORD_SIZE-1:0] q_in;
wire signed [ACC_WIDTH-1:0] phase_out;

// ===== Clock Generation =====
initial begin
    clk = 0;
    forever begin 
        #(PERIOD/2);
        clk = ~clk;
    end
end

// ===== DUT Instantiation =====
ipll dut (
    .clk(clk),
	 .clk_en(clk_720),
    .reset(reset),
    .q_in(q_in),
    .freq_out(phase_out) //output frequency which goes into dqz
);

/*
igff #(
    .WORD_SIZE(WORD_SIZE),
    .ACC_WIDTH(ACC_WIDTH)
) dut (
    .clk(clk),
    .reset(reset),
    .quad_in(q_in),
    .freq_out(phase_out) //output frequency which goes into dqz
);
*/
dqz dqz_inst (
  .clk(clk),
  .clk_en(clk_720),
  .reset(reset),
  .a_in(sig_a),
  .b_in(sig_b),
  .c_in(sig_c),
  .freq_in(phase_out), // Should be phase out
  //.sine(sig_s),
  //.cosine(sig_cos),
  .d_out(d_out),
  .q_out(q_in) //Output q which goes into ipll
);

integer freq_file;

initial begin
    // Open the file for writing
	 /*
	 Files we want for plots: 
	 J pos "f_out_hardware_J_FULLPOS_70000.txt" - bricked as soon as a change happened - makes sense
	 J pos "f_out_hardware_J_FULLPOS_60000.txt" - Fast!
	 J pos "f_out_hardware_J_FULLPOS_30000.txt" - 
	 J pos "f_out_hardware_J_FULLPOS_15000.txt" - 
	 J pos "f_out_hardware_J_FULLPOS_1500.txt" - 
	 J 0 
	 J neg "f_out_hardware_J_NEG_60000.txt" - 
	 J neg "f_out_hardware_J_NEG_30000.txt" - 
	 J neg "f_out_hardware_J_NEG_15000.txt" - 
	 J neg "f_out_hardware_J_NEG_1500.txt" - Doing now
	 
	 D full Pos
	 D half pos 
	 D 0 
	 D half neg 
	 D full neg 
	 
	 J and D full 
	 J and D half 
	 J and D 0 
	 J and D full neg 
	 J and D half neg 
	 */
    freq_file = $fopen("MATH_CF_61_LONG_D12_J005.txt", "w");
	 $display("OPENING f_out_hardware_B0_58235.txt");
    if (freq_file == 0) begin
        $display("Error: Could not open file for writing.");
        $finish;
    end
end

// Log the data every time the system updates (at the 720Hz rate)
always @(posedge clk) begin
    if (clk_720 && !reset) begin
        // %h writes in hex, %d for decimal. 
        // Hex is usually safer for 32-bit unsigned values to avoid sign-bit confusion.
        $fwrite(freq_file, "%h\n", phase_out); 
    end
end


// ===== Test Stimulus =====
initial begin
  // Initialize signals
  
  reset = 1;
  theta = 32'sd363879174; // 61 Hz response
  #(PERIOD * 5);
  reset = 0;
  #(PERIOD * 2048);

/* reset = 1;
  q_in = 10'b0;

  // Hold reset for 5 cycles
  repeat (5) @(posedge clk);
  reset = 0;

  // Unit Impulse
  @(posedge clk);
  q_in = 18'sd1310;

  @(posedge clk);
  q_in = 18'sd0;
  repeat (80) @(posedge clk);

  // Unit Step
  @(posedge clk);
  q_in = 18'sd1310;
  repeat (80) @(posedge clk); */

end

final begin
     $fclose(freq_file);
    $display("Hardware frequency data saved to f_out_hardware.txt");
end
endmodule