module dqz_tb;
// K - so we got our testbench signals all the same length right now - 16 bits
// And - all our inputs in the actual module are 16 bits
// At this point I have proven it's not a bit error on the tb side or the matlab side, though 
// there may be something happening that is not quite right in the actual math
// are we even sign extending? 

// Ah - I likely fucked some shit up by making the inputs 16 bits - but I say you should stick with the matlab 
// and testbench that is here and try to work on the actual module instead. 
localparam PERIOD = 10;
localparam DATA_WIDTH = 16; // 16-bit signed data
localparam ADDR_WIDTH = 10;

localparam [31:0] FCW_60HZ = 32'sd357913941;

integer i, k;
reg clk;
reg clk_720;
reg reset;
reg [ADDR_WIDTH-1:0] addr_cnt;
reg [31:0] theta;

// Memory arrays for stimulus
reg signed [DATA_WIDTH-1:0] mem_phase_a     [0:1023];
reg signed [DATA_WIDTH-1:0] mem_phase_b     [0:1023];
reg signed [DATA_WIDTH-1:0] mem_phase_c     [0:1023];
reg signed [DATA_WIDTH-1:0] mem_sine_ramp   [0:1023];
reg signed [DATA_WIDTH-1:0] mem_cosine_ramp [0:1023];


// Wires to connect to UUT
wire signed [DATA_WIDTH-1:0] sig_a, sig_b, sig_c;
wire signed [DATA_WIDTH-1:0] sig_s, sig_cos;
wire signed [17:0] d_out, q_out;

// 1. Load the Hex files generated by MATLAB
initial begin
    $readmemh("grid_a.hex",     mem_phase_a);
    $readmemh("grid_b.hex",     mem_phase_b);
    $readmemh("grid_c.hex",     mem_phase_c);
    $readmemh("sine_ramp.hex",   mem_sine_ramp);
    $readmemh("cosine_ramp.hex", mem_cosine_ramp);
    
    $display("Data loaded into testbench memories.");
end

// Clock generation (OK to use hardcoded delays #)
initial begin
  clk = 0;
  forever begin 
      #(PERIOD/2);
      clk = ~clk;
    end
end

// 3. Address Counter / Sequencer
 localparam CLK_FREQ_HZ     = 25_000_000;  // 25 MHz System Clock
 localparam SAMPLE_RATE_HZ  = 720;         // Target Data Rate
 localparam CLKS_PER_SAMPLE = CLK_FREQ_HZ / SAMPLE_RATE_HZ; // ~34,722 clocks

 integer timer_cnt;

 // 3. Address Counter / Sequencer (Modified for 720 Hz rate)
 // ALSO - HERE WE MAKE OUR 720 CLK ENABLE CALLED CLK 720
always @(posedge clk or posedge reset) begin
    if (reset) begin
      addr_cnt  <= 11'd0;
      timer_cnt <= 0;
      clk_720 <= 1'd0;
    end else begin
      // Check if enough clock cycles have passed to jump to the next sample
      if (timer_cnt >= CLKS_PER_SAMPLE - 1) begin
            timer_cnt <= 0;               // Reset timer
            clk_720 <= 1;
            
            // Seamless wrap logic:
            if (addr_cnt >= 11'd1199) begin
                addr_cnt <= 11'd0;        // Loop back to start of cycle
            end else begin
                addr_cnt <= addr_cnt + 11'd1; 
            end
            
      end else begin
            timer_cnt <= timer_cnt + 1;
            clk_720 <= 0;
      end
    end
 end
// 4. Assign memory values to UUT input wires
assign sig_a   = mem_phase_a[addr_cnt];
assign sig_b   = mem_phase_b[addr_cnt];
assign sig_c   = mem_phase_c[addr_cnt];
assign sig_s   = mem_sine_ramp[addr_cnt];
assign sig_cos = mem_cosine_ramp[addr_cnt];

initial begin
  // Initialize signals
  reset = 1;
  theta = 10'b0;
  #(PERIOD * 5);
  reset = 0;

  theta = FCW_60HZ; // So right now, in the dqz testbench, freq of sine and a are the same, so you would think q or d out would be 0 perfectly, but they arent
  // note - very importantly - that sine and sig_a are of different bit lengths! 
  // q is oscillating - even when the damn frequency is right!!!! EVEN WHEN ITS ON PHASE!!!! PERFECTLY!!!!
  /// so then - DQZ IS FUCKED - IT IS NOT THE PLL - GOD DAMN
  
  // Run for two full cycles of the 1024-sample buffer
  #(PERIOD * 2048);
  
end

dqz dqz_inst (
  .clk(clk),
  .clk_en(clk_720),
  .reset(reset),
  .a_in(sig_a),
  .b_in(sig_b),
  .c_in(sig_c),
  .freq_in(theta),
  //.sine(sig_s),
  //.cosine(sig_cos),
  .d_out(d_out),
  .q_out(q_out)
);

endmodule