// issp_control.v

// Generated using ACDS version 22.1 922

`timescale 1 ps / 1 ps
module issp_control (
		input  wire [63:0] probe,      //     probes.probe
		input  wire        source_clk, // source_clk.clk
		output wire [99:0] source      //    sources.source
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("IPLL"),
		.probe_width             (64),
		.source_width            (100),
		.source_initial_value    ("000F05283FAFC9D3007A83817"),
		.enable_metastability    ("YES")
	) in_system_sources_probes_0 (
		.source     (source),     //    sources.source
		.source_clk (source_clk), // source_clk.clk
		.probe      (probe),      //     probes.probe
		.source_ena (1'b1)        // (terminated)
	);

endmodule
